'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.18444
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class CAcert_CSR_UI
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CAcert_CSR.CAcert-CSR_UI", GetType(CAcert_CSR_UI).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property btnClear() As String
            Get
                Return ResourceManager.GetString("btnClear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alles Löschen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property btnClearAll() As String
            Get
                Return ResourceManager.GetString("btnClearAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;OK ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property btnOK() As String
            Get
                Return ResourceManager.GetString("btnOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mit CAcert fertigstellern ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_btnCAcertFin() As String
            Get
                Return ResourceManager.GetString("csr_btnCAcertFin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Von CAcert in Datei speichern ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_btnCAcertSave() As String
            Get
                Return ResourceManager.GetString("csr_btnCAcertSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mit CAcert signieren ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_btnCAcertSig() As String
            Get
                Return ResourceManager.GetString("csr_btnCAcertSig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die CSR erstellen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_btnGenerate() As String
            Get
                Return ResourceManager.GetString("csr_btnGenerate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Art ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_gbArt() As String
            Get
                Return ResourceManager.GetString("csr_gbArt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Typ ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_gbTyp() As String
            Get
                Return ResourceManager.GetString("csr_gbTyp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_inputBoxPrompt() As String
            Get
                Return ResourceManager.GetString("csr_inputBoxPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Weiterer Name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_inputBoxTitle() As String
            Get
                Return ResourceManager.GetString("csr_inputBoxTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Klasse ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_lblClass() As String
            Get
                Return ResourceManager.GetString("csr_lblClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Allgemeiner Name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_lblCommon() As String
            Get
                Return ResourceManager.GetString("csr_lblCommon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Weitere Namen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_lblNamen() As String
            Get
                Return ResourceManager.GetString("csr_lblNamen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bitte die CCA akzeptieren. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_msgCCA() As String
            Get
                Return ResourceManager.GetString("csr_msgCCA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wurde noch nicht umgesetzt. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_msgNotAvailable() As String
            Get
                Return ResourceManager.GetString("csr_msgNotAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die OpenSLL wurde nicht gefunden. Bitte installiern Sie es in den Pfad {0} nach. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_msgOpenSSL() As String
            Get
                Return ResourceManager.GetString("csr_msgOpenSSL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stelel auf Privat um. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_msgTurnPrivate() As String
            Get
                Return ResourceManager.GetString("csr_msgTurnPrivate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Client ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_rbClient() As String
            Get
                Return ResourceManager.GetString("csr_rbClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Organisation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_rbOrganisation() As String
            Get
                Return ResourceManager.GetString("csr_rbOrganisation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Private ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_rbPrivate() As String
            Get
                Return ResourceManager.GetString("csr_rbPrivate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Server ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_rbServer() As String
            Get
                Return ResourceManager.GetString("csr_rbServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die CSR Bestätigung ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_strWoConfirmation() As String
            Get
                Return ResourceManager.GetString("csr_strWoConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die CSR Eingabe ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_strWoCSR() As String
            Get
                Return ResourceManager.GetString("csr_strWoCSR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anmelden ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_strWoLogin() As String
            Get
                Return ResourceManager.GetString("csr_strWoLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abmelden ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_strWoLogout() As String
            Get
                Return ResourceManager.GetString("csr_strWoLogout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SIG erzeugen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_strWoSig() As String
            Get
                Return ResourceManager.GetString("csr_strWoSig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Browser Start ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_strWoStart() As String
            Get
                Return ResourceManager.GetString("csr_strWoStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Erzeugen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property csr_tpCreate() As String
            Get
                Return ResourceManager.GetString("csr_tpCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anmelden mit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_gbLogin() As String
            Get
                Return ResourceManager.GetString("ext_gbLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_lblAccLogin() As String
            Get
                Return ResourceManager.GetString("ext_lblAccLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Logout ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_lblAccLogout() As String
            Get
                Return ResourceManager.GetString("ext_lblAccLogout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Organisations Client Zertifikat ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_lblOrgClient() As String
            Get
                Return ResourceManager.GetString("ext_lblOrgClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ogranisations Server Zertifikat ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_lblOrgServer() As String
            Get
                Return ResourceManager.GetString("ext_lblOrgServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Produktiv Server (Zertifikat) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_lblProdCertServ() As String
            Get
                Return ResourceManager.GetString("ext_lblProdCertServ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Produktiv Server (Passwort) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_lblProdPassServ() As String
            Get
                Return ResourceManager.GetString("ext_lblProdPassServ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Test Server (Zertifikat) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_lblTestCertServer() As String
            Get
                Return ResourceManager.GetString("ext_lblTestCertServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Test Server (Password) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_lblTestPassServer() As String
            Get
                Return ResourceManager.GetString("ext_lblTestPassServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Privates Client Zeritfikat ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_lblUserClient() As String
            Get
                Return ResourceManager.GetString("ext_lblUserClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Privates Server Zertifikat ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_lblUserServer() As String
            Get
                Return ResourceManager.GetString("ext_lblUserServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bitte eine Auswahl bei &apos;Anmelden mit&apos; machen. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_msgLogin() As String
            Get
                Return ResourceManager.GetString("ext_msgLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zertifikat ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_rbCertificate() As String
            Get
                Return ResourceManager.GetString("ext_rbCertificate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Passwort ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_rbPassword() As String
            Get
                Return ResourceManager.GetString("ext_rbPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Erweiterte Einstellungen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ext_Title() As String
            Get
                Return ResourceManager.GetString("ext_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Language_DE() As String
            Get
                Return ResourceManager.GetString("Language_DE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Englisch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Language_EN() As String
            Get
                Return ResourceManager.GetString("Language_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Datei ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mnuFile() As String
            Get
                Return ResourceManager.GetString("mnuFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Hilfe ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mnuHelp() As String
            Get
                Return ResourceManager.GetString("mnuHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Info ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mnuInfo() As String
            Get
                Return ResourceManager.GetString("mnuInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Sprache ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mnuLanguage() As String
            Get
                Return ResourceManager.GetString("mnuLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Beenden ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mnuQuit() As String
            Get
                Return ResourceManager.GetString("mnuQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Einstellungen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mnuSettings() As String
            Get
                Return ResourceManager.GetString("mnuSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Optionen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mnuTools() As String
            Get
                Return ResourceManager.GetString("mnuTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property msgTitleError() As String
            Get
                Return ResourceManager.GetString("msgTitleError", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
